### ISSUE TITLE
Change Code39 to Code128

### ISSUE THREAD

**Issue by jarscr** [envisiondata/cordova-plugin-starprinter#4]
Hello,

I try many method for change code print. but can't decode the hex.
StarPrinter.java
list.add(new byte[] { 0x1d, 0x77, 0x02 }); // for 1D Code39 Barcode
			list.add(new byte[] { 0x1d, 0x68, 0x64 }); // for 1D Code39 Barcode
			list.add(new byte[] { 0x1d, 0x48, 0x01 }); // for 1D Code39 Barcode
			list.add(new byte[] { 0x1d, 0x6b, 0x41, 0x0b, 0x30, 0x30, 0x30,0x30, 0x30, 0x30, 0x31, 0x39, 0x31, 0x33, 0x32 });

The manual from Star doesn't work for decode you hex use in the file StarPrinter.java.

Modify all data in Receipt, but this code I fail.

Thanks for you help.

Regards

**Comment by envisiondata** [comment]
Alfredo,
I looked and that is what they have for the 1D bar code as an example. I'm not sure how to interpret the hex value. You could email their support and find out what you need. They are very helpful.
Sorry I wan not more help.
James

**Comment by jarscr** [comment]
Hello,

I use documents in the Web StarMicro, but the commands doesn't equal sample code.

The code commands in the example is
GS w 2 
GS h d
GS H 1
GS K A VT 00000019132

I the manual I have "StarIO_ESCPOS_PortablePrinter_Android_SDK.pdf" have this command for Barcode 128.
GS h 3
GS w 5
GS k 6 5 19132
If you have manual for example use in this plugin, I'm glad for your help.

REgards

**Comment by jarscr** [comment]
Hello, I solve the problem.

This is the code for CODE128

list.add(new byte[] { 0x1d, 0x77, 0x03 }); // for 1D Code39 Barcode
			list.add(new byte[] { 0x1d, 0x68, 0x64 }); // for 1D Code128 Barcode
			list.add(new byte[] { 0x1d, 0x48, 0x01 }); // for 1D Code128Barcode
			list.add(new byte[] { 0x1d, 0x6b, 0x46, 0x0b, 0x30,0x30,0x30,0x34, 0x32, 0x30, 0x33, 0x34, 0x30, 0x35, 0x36 });

//0x30,0x30,0x30,0x34, 0x32, 0x30, 0x33, 0x34, 0x30, 0x35, 0x36 CODE NUMBER 000042034056

Regards
